# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-10 21:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('deleted_at', models.DateTimeField(verbose_name='Deleted at')),
                ('uuid', models.UUIDField(default=uuid.UUID('c6eb5c4f-f00e-4b11-ba1e-2a1ed4611d59'), unique=True)),
                ('name', models.CharField(max_length=64, verbose_name='Category name')),
                ('user', models.ManyToManyField(related_name='categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-updated_at', '-created_at'),
                'abstract': False,
                'get_latest_by': 'updated_at',
            },
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('deleted_at', models.DateTimeField(verbose_name='Deleted at')),
                ('uuid', models.UUIDField(default=uuid.UUID('68b097d8-5757-4f4e-9806-1aa16aa85341'), unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='core.Category')),
            ],
            options={
                'ordering': ('-updated_at', '-created_at'),
                'abstract': False,
                'get_latest_by': 'updated_at',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('deleted_at', models.DateTimeField(verbose_name='Deleted at')),
                ('uuid', models.UUIDField(default=uuid.UUID('d0150cea-dbf8-40fa-8aae-2c7b95700484'), unique=True)),
                ('name', models.CharField(max_length=128, verbose_name='Item name')),
            ],
            options={
                'ordering': ('-updated_at', '-created_at'),
                'abstract': False,
                'get_latest_by': 'updated_at',
            },
        ),
        migrations.AddField(
            model_name='entry',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='core.Item'),
        ),
        migrations.AddField(
            model_name='entry',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to=settings.AUTH_USER_MODEL),
        ),
    ]
