# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-30 15:24
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='deleted_at',
            field=models.DateTimeField(null=True, verbose_name='Deleted at'),
        ),
        migrations.AlterField(
            model_name='category',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('6d8f0138-64c4-454b-a02e-933e972feb6e'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='deleted_at',
            field=models.DateTimeField(null=True, verbose_name='Deleted at'),
        ),
        migrations.AlterField(
            model_name='debitcard',
            name='deleted_at',
            field=models.DateTimeField(null=True, verbose_name='Deleted at'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='deleted_at',
            field=models.DateTimeField(null=True, verbose_name='Deleted at'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('cc1aeee5-933e-4b03-b8fb-2033e8027ccc'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='deleted_at',
            field=models.DateTimeField(null=True, verbose_name='Deleted at'),
        ),
        migrations.AlterField(
            model_name='item',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('4f38313f-3beb-4621-bc64-c4ee5e1d6bcb'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='deleted_at',
            field=models.DateTimeField(null=True, verbose_name='Deleted at'),
        ),
    ]
