# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-19 18:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180330_1524'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='entry',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='item',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='entry',
            name='date',
            field=models.DateField(default=datetime.date(2018, 4, 19), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='category',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('eeccffb1-7b24-4ac0-9461-56557d72d175'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='entry',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('4e1f4947-e596-4ccc-846f-1f8854b8f90c'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('3fd45f9f-f7d2-42f0-92ff-be71448663d1'), primary_key=True, serialize=False),
        ),
    ]
