# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-19 19:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180419_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='price',
            field=models.FloatField(default=0., verbose_name='Price'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entry',
            name='quantity',
            field=models.FloatField(default=0., verbose_name='Quantity'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entry',
            name='total',
            field=models.FloatField(default=0., verbose_name='Total'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('2ff18f41-6dd2-43fa-94c5-02d14c7912a8'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='entry',
            name='date',
            field=models.DateField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('c0c24d4f-fe03-4b99-a434-caef0746cadc'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('63b06e08-db5b-401e-87e6-be08cd04db6b'), primary_key=True, serialize=False),
        ),
    ]
