# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-19 19:51
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20180419_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('d19e724c-67bb-478d-ad50-598ff2e28b25'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='entry',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('8533a379-64d5-4f84-b165-8647d5c807b2'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('e1304e16-808b-4c71-9165-4848000cc991'), primary_key=True, serialize=False),
        ),
    ]
